[package]
name = "spaced"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.12"
termion = "1.5"
clap = { version = "~2.27.0", features = ["yaml", "color"] }
walkdir = "2"
serde = "1.0"
serde_yaml = "0.8"
chrono = "0.4"
