[package]
name = "spaced"
version = "0.1.0"
edition = "2018"
build = "build.rs"

[build-dependencies]
clap = { version = "~2.27.0" }

[dependencies]
tui = "0.12"
termion = "1.5"
clap = { version = "~2.27.0" }
walkdir = "2"
serde_yaml = "0.8"
chrono = "0.4"
